### ISSUE TITLE
Lumen 5.4  OPTIONS request returns 405

### ISSUE THREAD

**Issue by zhaoqy** [barryvdh/laravel-cors#175] opened 2017-02-13 05:28 UTC
Lumen 5.3 is OK , Lumen  5.4 is not support?

**Lumen (5.4.4) (Laravel Components 5.4.*)**
```
"laravel/lumen-framework": "5.4.*",
"illuminate/redis": "^5.4",
"illuminate/mail": "^5.4",
"illuminate/routing": "^5.4",
"barryvdh/laravel-cors": "^0.8.5",
```
**bootstrap/app.php**
```
$app->middleware([
    Barryvdh\Cors\HandleCors::class
]);
$app->routeMiddleware([
   // .... others middleware
    'cros' => \Barryvdh\Cors\HandleCors::class
]);
$app->register(Barryvdh\Cors\LumenServiceProvider::class);
$app->configure('cors');  
```

**Route:**
```
$app->group(['prefix' => 'v1', 'namespace' => 'V1', 'middleware' => ['cros']], function ($app) {

});
```

**config:**
```
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
```

**HTTP:**
```
Request URL:http://test.api.sudaizhijia.com/v1/product/promotion
Request Method:OPTIONS
Status Code:405 Method Not Allowed

Response Headers
view source
Access-Control-Allow-Headers:*
Access-Control-Allow-Origin:http://test.m.sudaizhijia.com
Allow:GET
Cache-Control:no-cache, private
Connection:keep-alive
Content-Type:text/html; charset=UTF-8
Date:Mon, 13 Feb 2017 05:16:15 GMT
Server:nginx
Transfer-Encoding:chunked
Vary:Origin
X-Powered-By:PHP/5.6.28

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:x-token
Access-Control-Request-Method:GET
Cache-Control:max-age=0
Connection:keep-alive
Host:test.api.sudaizhijia.com
Origin:http://test.m.sudaizhijia.com
Referer:http://test.m.sudaizhijia.com/
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

```
Stack trace:

```
#0 /ynw/website/test.api.sudaizhijia.com/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(533): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#2 /ynw/website/test.api.sudaizhijia.com/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#3 /ynw/website/test.api.sudaizhijia.com/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#4 /ynw/website/test.api.sudaizhijia.com/vendor/illuminate/pipeline/Pipeline.php(148): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#6 /ynw/website/test.api.sudaizhijia.com/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /ynw/website/test.api.sudaizhijia.com/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /ynw/website/test.api.sudaizhijia.com/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 /ynw/website/test.api.sudaizhijia.com/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#10 /ynw/website/test.api.sudaizhijia.com/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#11 /ynw/website/test.api.sudaizhijia.com/public/index.php(28): Laravel\Lumen\Application->run()
#12 {main}  

```

**Comment by zhaoqy** [comment] 2017-02-13 10:30
Solution: remove HandleCors class to the global $middleware section.

```
$app->middleware([
    //Barryvdh\Cors\HandleCors::class
]);
```

**Comment by zhaoqy** [comment] 2017-02-13 12:30
**I directly change the source.**
**Solved**: add HandlePreflightSimpleclass to the global $middleware section.
```
$app->middleware([
    \Barryvdh\Cors\HandlePreflightSimple::class
]);
```

change Barryvdh\Cors\HandlePreflightSimple
from:
```
$preflight = $this->cors->handlePreflightRequest($request);
$response->headers->add($preflight->headers->all());
```
to:
`$response = $preflight = $this->cors->handlePreflightRequest($request);
`

**Hope the author fixes it**

**Comment by barryvdh** [comment] 2017-02-13 12:40
Shouldn't that have the same effect?

It should be added with https://github.com/barryvdh/laravel-cors/blob/master/src/LumenServiceProvider.php#L48

**Comment by zhaoqy** [comment] 2017-02-13 12:59
@barryvdh 

Not work. This logic condition is not executed.

$request = app(Request::class);   
The value of $request http method is GET, not a OPTIONS request.

**Comment by barryvdh** [comment] 2017-02-13 13:16
But preflight is for OPTIONS, niet for GET

**Comment by zhaoqy** [comment] 2017-02-13 13:48
@barryvdh 

From my upgrade from lumen5.3 to lumen5.4
As follows：

Request Method:OPTIONS

Request Header:
```
Access-Control-Request-Headers:x-token
Access-Control-Request-Method:GET
```

Response Header:
`Allow:GET`

Not set up
Response Header:
```
access-control-allow-headers:X-TOKEN
access-control-allow-methods:GET
Access-Control-Allow-Origin:http://test.m.sudaizhijia.com
```

**Comment by pvormittag** [comment] 2017-02-13 18:30
I can confirm this issue on 5.4.

It's due to https://github.com/laravel/lumen-framework/issues/565, causing https://github.com/barryvdh/laravel-cors/blob/master/src/LumenServiceProvider.php#L41 to always return `false`.

Review the thread on this PR for a possible / recommended solution: https://github.com/laravel/lumen-framework/pull/568. It appears this package will need some refactoring in order to work in 5.4.

**Comment by austenc** [comment] 2017-02-13 18:34
@barryvdh I was in the process of submitting a pull request to fix this -- you can combine the service provider logic and middleware logic into just a middleware.

**Comment by austenc** [comment] 2017-02-13 18:44
On second thought @barryvdh it might be better if you make this change as removing the service provider would break backwards compatibility for your package, so I'm not sure how you'd like to handle that. Maybe a new middleware for 5.4+ ? 

Let me know if you need help reproducing or testing!

**Comment by barryvdh** [comment] 2017-02-13 18:50
So isn't this an upstream issue?

**Comment by austenc** [comment] 2017-02-13 19:05
Apparently not... my pull request laravel/lumen-framework#568 was closed. I agree that this seems like a breaking change that should be more akin to a major version number release, but I'm not sure what else we can do. Regardless though, this does make a lot of sense for lumen and this type of logic really _should_ probably be handled by middleware.

**Comment by barryvdh** [comment] 2017-02-13 19:16
Yeah I agree, perhaps it would be better to move it all to the middleware.

I'm thinking about stripping some options and just use 1 global pre-flight middleware want route middleware.

**Comment by austenc** [comment] 2017-02-13 19:22
I have not tested if the global middleware-only approach works with 5.3, but adding the `if ($request->isMethod('OPTIONS')` chunk to the CorsMiddleware does indeed fix the issue on 5.4.

**Comment by barryvdh** [comment] 2017-02-13 22:20
Can you check out https://github.com/barryvdh/laravel-cors/pull/176 ?

That just uses the middleware for everything. Same service provider for Lumen, but different middleware.

**Comment by austenc** [comment] 2017-02-14 00:59
@barryvdh I tested it and I got `Origin not allowed` -- it seems the `$options` var isn't being instantiated properly when the CorsService is created? Here's a simple middleware I was using to have it work with 5.4 earlier -- maybe it will help? Note that it runs both before and after the response is created! 

```
<?php namespace App\Http\Middleware;
class CorsMiddleware {
  public function handle($request, \Closure $next)
  {

    if ($request->isMethod('OPTIONS')) {
      app()->options($request->path(), function() { return response('', 200); });
    }

    $response = $next($request);
    $response->header('Access-Control-Allow-Methods', 'HEAD, GET, POST, PUT, PATCH, DELETE');
    $response->header('Access-Control-Allow-Headers', $request->header('Access-Control-Request-Headers'));
    $response->header('Access-Control-Allow-Origin', '*');
    return $response;
  }
}
```

**Comment by barryvdh** [comment] 2017-02-14 06:08
Did you add the service provider?

**Comment by zhaoqy** [comment] 2017-02-14 09:55
@barryvdh 
I am temporarily changing the code by my way., add the LumenServiceProvider to bootstrap/app.php

If you remove it, origin check will not pass it.

Look forward to your complete fix

**Comment by barryvdh** [comment] 2017-02-14 13:58
I've updated the code, can you try that PR (by requiring `dev-develop` or `1.x@dev`) and follow the readme from https://github.com/barryvdh/laravel-cors/tree/develop

**Comment by austenc** [comment] 2017-02-14 14:17
@barryvdh I did _not_ add the service provider last time, as I was just testing with Lumen and I thought that the `$app->configure('cors')` would take its place in lumen's case. I'll test the latest code this morning and get back to you

**Comment by austenc** [comment] 2017-02-14 14:22
@barryvdh Working great on Lumen 5.4 with only `$app->configure('cors')` and global middleware in `bootstrap/app.php`, nice job, and thank you!

**Comment by barryvdh** [comment] 2017-02-14 14:30
Without adding the service provider, I don't think the options were used. But I now changed it so the ServiceProvider isn't really needed at all.

**Comment by apoca** [comment] 2017-02-23 23:44
My problem continue... 501 method not implemented... I Fellow Your last dev version..

**Comment by boonstoppel** [comment] 2017-02-27 16:28
I'm using  laravel/lumen-framework (v5.4.4) and barryvdh/laravel-cors (dev-develop 22eff73). 

I still get a 403 Response for preflight requests: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Tried adding it as global middleware and also a group middleware. Adding both \Barryvdh\Cors\HandleCors::class and \Barryvdh\Cors\HandlePreflight::class.

Versions  laravel/lumen-framework (v5.4.1) with barryvdh/laravel-cors (V0.8.4) works fine.

**Comment by Donatello-za** [comment] 2017-03-15 09:14
I get a similar problem but with error 400 being returned instead of 405 and I think it may be related. This is with Lumen v5.4.5 together with barryvdh/laravel-cors (v0.8.4, v0.8.6 and dev-develop), all returns error 400 on the OPTIONS request that goes out to the server.

I have at this point only tried it with global middleware, i.e.:
```php
$app->middleware([
    \Barryvdh\Cors\HandleCors::class
]);

$app->register(Barryvdh\Cors\LumenServiceProvider::class);

$app->configure('cors');
```

With the dev-develop branch I have to comment out `$app->register(Barryvdh\Cors\LumenServiceProvider::class);`

My configuration looks as follows:
```
return [
    'supportsCredentials' => true,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE'],
    'exposedHeaders' => ['Authorization'],
    'maxAge' => 0,
    'hosts' => [],
];
```

**Comment by Donatello-za** [comment] 2017-03-15 10:37
Ok, so I managed to get the error 400 to go away, I think it was partly caused by the client not sending the CORS headers on my side, so at the moment I'm on barryvdh/laravel-cors dev-develop and I do not include the `
$app->register(Barryvdh\Cors\LumenServiceProvider::class);` line any more.

However, I'm now dealing with the browser stating: "`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://xyz. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`"

I've stepped through the code and the pre-flight check is working and the correct headers are returned, even the `Access-Control-Allow-Origin` header, so I'm not sure why the browser is saying it is missing.

**Comment by Donatello-za** [comment] 2017-03-15 11:14
Ok, one step forward, two steps back, sorry for spamming this issue. It seems that the pre-flight check succeeds, but the followup request fails because the CORS headers are not being returned. Stepping through the code the following section in `HandleCors.php` seems to be a problem:

```php
		// Add the headers on the Request Handled event
		if (class_exists(RequestHandled::class)) {
            $this->events->listen(RequestHandled::class, function(RequestHandled $event) use ($cors) {
                $cors->addActualRequestHeaders($event->response, $event->request);
            });
        } else {
            $this->events->listen('kernel.handled', function($request, $response) use ($cors) {
                $cors->addActualRequestHeaders($response, $request);
            });
        }
```

Since this is Lumen and not Laravel, the RequestHandled class is not available as it forms part of the Foundation classes of Lumen. This means that the following event listener is setup:

```
            $this->events->listen('kernel.handled', function($request, $response) use ($cors) {
                $cors->addActualRequestHeaders($response, $request);
            });
```

The problem is that it doesn't work as the event handler is never called. I think it might be because this way of setting up the `'kernel.handled'` event is no longer supported in Laravel and since there is no RequestHandled class we are having this problem.

**Comment by barryvdh** [comment] 2017-03-15 13:25
Perhaps that isn't supported in Lumen. Need to find a way to test Lumen properly.

**Comment by barryvdh** [comment] 2017-03-15 13:39
I used the kernel event as fallback, can you try now with https://github.com/barryvdh/laravel-cors/commit/272a6b831a10118e294dc3805a4d841a50e7cecc?

**Comment by Donatello-za** [comment] 2017-03-15 14:50
Thanks Barry, that works. These types of events will not work in Lumen any more and I'm wondering if Taylor thought of that when he changed the functionality. Perhaps an issue should be created on [laravel/framework](https://github.com/laravel/framework) since I'm sure other Lumen developers also may have used the event functionality.

Before your latest commit (https://github.com/barryvdh/laravel-cors/commit/272a6b831a10118e294dc3805a4d841a50e7cecc) I did something similar:

```php
if (class_exists(RequestHandled::class)) {
    $this->events->listen(RequestHandled::class, function(RequestHandled $event) use ($cors) {
        $cors->addActualRequestHeaders($event->response, $event->request);
    });

    return $next($request);
} else {
    $response = $next($request);
    $cors->addActualRequestHeaders($response, $request);

    return $response;
}
```

I think your change covers more angles though, thanks for your help!

**Comment by barryvdh** [comment] 2017-03-15 16:23
For people testing the develop version, be aware that since https://github.com/barryvdh/laravel-cors/commit/dc67ff1d0e5f5e4fb6c8e91f82443d011fb3f5d4 you need to add the ServiceProvider instead of the preflight middleware directly.

Not yet tested on Lumen, only on automated Laravel tests. So let me know if you run into problems!

**Comment by barryvdh** [comment] 2017-03-20 14:35
Can you try with v0.9.x? See the updated readme, just 1 serviceprovider now.

**Comment by boonstoppel** [comment] 2017-03-20 16:32
barryvdh/laravel-cors (dev-master) with laravel/lumen-framework (v5.4.5) I still get "Response to preflight request doesn't pass access control check: Access-Control-Allow-Origin"

**Comment by barryvdh** [comment] 2017-03-20 16:35
And no errors in your logs? You added the ServiceProvider AND the middleware to the routes?

**Comment by boonstoppel** [comment] 2017-03-20 16:42
Ah, I didn't add the middleware. In Lumen the global middleware is added like so:
```
$app->middleware([
   \Barryvdh\Cors\HandleCors::class
]);
```

All works now. Thanks so much!

**Comment by barryvdh** [comment] 2017-03-20 17:26
Ah, can you add a Pr to the Readme if you think it can be explained better?

**Comment by brunofunny** [comment] 2017-04-04 15:18
I don't know if it happend only here when you posted but, there's a typo on you line " 'middleware' => ['cros']]" you're naming it CROS not CORS

**Comment by yesterday679** [comment] 2017-04-13 10:35
now fixed ?

**Comment by andrew-s** [comment] 2017-05-16 16:52
I'm still experiencing this issue on Lumen 5.4, I tried the last release at 0.9.2 and the commit 48f9ef58920e19614617d90538371840254a82af however I'm still receiving 405 on OPTION requests.

In my bootstrap;

```php
$app->configure('cors');
$app->middleware([
     \Barryvdh\Cors\HandleCors::class,
});
$app->register(Barryvdh\Cors\ServiceProvider::class);
```

And my config:

```php
return [
    /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |
     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
     | to accept any value.
     |
     */
    'supportsCredentials' => true,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
];
```

Any thoughts on this?

**Comment by shyandsy** [comment] 2017-06-02 19:10
looks there is no solution available now

**Comment by hakuno** [comment] 2017-06-12 18:26
Only middleware like [that](https://gist.github.com/danharper/06d2386f0b826b669552#gistcomment-2013919).

**Comment by rizqyhi** [comment] 2017-06-15 02:21
Hi, I'm running into this issue too with Lumen 5.4.6. My current setup is:
```
$app->configure('cors');
$app->middleware([
     \Barryvdh\Cors\HandleCors::class,
});
$app->register(Barryvdh\Cors\ServiceProvider::class);
```
I don't know is it relevant to this issue, but I got the following error in the log:
```
[2017-06-15 09:01:19] lumen.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Barryvdh\Cors\HandleCors::addHeaders() must be an instance of Symfony\Component\HttpFoundation\Response, null given, called in F:\uniserver\vhosts\gifood-api\vendor\barryvdh\laravel-cors\src\HandleCors.php on line 60 and defined' in F:\uniserver\vhosts\gifood-api\vendor\barryvdh\laravel-cors\src\HandleCors.php:68
Stack trace:
...
```
I tried [this](https://gist.github.com/danharper/06d2386f0b826b669552#gistcomment-2013919) too, but doesn't work at all. It shows a different error in the log, but the point is `$response` is always `null`.

**Comment by barryvdh** [comment] 2017-12-19 11:09
Are you all using it as global middleware, and is it working with non cross-domain requests properly? (no 404 etc?)

**Comment by barryvdh** [comment] 2017-12-19 21:12
Can you try with Can you try with https://github.com/barryvdh/laravel-cors/releases/tag/v0.10.1 ? 

Please open a separate issue when it still persists.

**Closed by barryvdh** 2017-12-19 21:12 UTC

**Comment by lnpbk** [comment] 2018-01-17 23:55
I know this is closed, but I was struggling with this issue for a while, and this may help someone.

It turned out that my request was to a destination that actually existed as a folder in my public directory.

My JS was requesting `POST http://api.mysite.com/images`, and `/public/images` existed.

To fix the issue I changed the route and request endpoint to something other than the folder name (in my case `/image-upload`)

**Comment by trogne** [comment] 2019-01-31 04:34
Still no "cors" solutions for recent "axios.post" and Lumen ?

**Comment by trogne** [comment] 2019-01-31 04:39
> 
> 
> Only middleware like [that](https://gist.github.com/danharper/06d2386f0b826b669552#gistcomment-2013919).

That solution is not working either.
