### ISSUE TITLE
Laravel 5.2 API Middleware Group Doesn't Work When Adding CORS

### ISSUE THREAD

**Issue by mtpultz** [barryvdh/laravel-cors#103] opened 2016-02-24 00:53 UTC
I can get access to the server using either `cors` or `['cors', 'api']` as my API route group middleware, but when adding CORS to the middleware group using API route group middleware of `api` doesn't work.

Checked that I had things working using:

```
    protected $middleware = [
        // ...
        \Barryvdh\Cors\HandleCors::class, // works when added to everything
    ];
```

Then changed my routes to use just the middleware and removed the above middleware:

```
    protected $routeMiddleware = [
        // ...
        'cors'       => \Barryvdh\Cors\HandleCors::class, // works when added manual to routes or route groups
    ];
}
```

Finally, tried to add it to the middleware group API, but it doesn't work saying that `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

```
Route::group([
    'prefix'     => 'api/v1',
    'middleware' => 'cors', 
  
     // NOTE: also works with ['cors', 'api'] as long as CORS not added to API middleware group, 
     // and equivalent ['cors', 'throttle:60,1'], but never works for `api` if CORs added to API 
     // middleware group

], function () {

    Route::group([
        'prefix'     => 'auth', 'middleware' => 'guest',
    ], function () {
        // ...
    });

    Route::group([
        'prefix'     => 'restricted',
        'middleware' => 'auth:api',
    ], function () {
        // ...
    });
});
```

**CORS Configuration**

```
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 3600,
    'hosts' => [],
```

**Comment by henritoivar** [comment] 2016-03-02 15:17
+1

**Comment by pashamesh** [comment] 2016-03-10 23:03
+1

**Comment by LoveAndHappiness** [comment] 2016-03-13 03:48
I don't even get an error message. It just doesn't work, neither as global middleware, nor as normal middleware.

Here is a fresh installation of Laravel 5.2.22 and laravel-cors 0.8: https://github.com/LoveAndHappiness/laravel-cors-example

Would be nice, if anyone could clone it and check if the error is reproduceable.

Thanks

**Comment by jonmorrison99** [comment] 2016-03-16 17:34
+1

**Comment by Utwo** [comment] 2016-03-22 17:54
+1

**Comment by csprocket777** [comment] 2016-03-23 04:06
+1

**Comment by danwomersley** [comment] 2016-03-30 15:39
+1

**Comment by webappbuilder** [comment] 2016-03-30 20:39
+1

**Comment by Blizzke** [comment] 2016-04-19 13:49
I have the same issue, it's because the preflight only checks [either the global middlewares](https://github.com/barryvdh/laravel-cors/blob/master/src/HandlePreflight.php#L48) or the [ones directly assigned to the route](https://github.com/barryvdh/laravel-cors/blob/master/src/HandlePreflight.php#L57), it doesn't expand middlewares from the `middlewareGroups` to check their associated middlewares. 

Suppose you have assigned the routes to the `middlewareGroups` "web", it will just get an array containing  "web". The check doesn't see cors, so it's not a cors request ergo no headers. 

I really hate having to explicitly add "cors" to all my group statementss for this to work. 
I just want to be able to add the cors to a `middlewareGroup` and just use one.

**Comment by rochapablo** [comment] 2016-05-20 17:48
+1 #89

**Comment by designvoid** [comment] 2016-05-31 13:44
+1 tried everything to get this working but to no avail

**Comment by VivekManglani** [comment] 2016-07-01 17:18
+1

**Closed** 2016-07-01 19:05 UTC

**Comment by rockymontana** [comment] 2016-07-03 16:46
@barryvdh - I see you closed this issue - Does that mean that this is fixed, or is there anything one need to do to get around this issue? I've got it too 🈂️

**Comment by designvoid** [comment] 2016-07-04 12:52
It has been fixed by the looks of it:

https://github.com/barryvdh/laravel-cors/pull/114
